var valor = parseInt(prompt())  
var cem = parseInt (valor / 100) 
valor = valor - (cem * 100) 
var cinquenta = parseInt (valor / 50)
valor = valor - (cinquenta * 50)
var dez = parseInt (valor / 10)
valor = valor - (dez * 10)
var cinco = parseInt (valor / 5)
valor = valor - (cinco * 5)
var um = parseInt (valor / 1)

console.log(cem + " notas de 100 ")
console.log(cinquenta + " notas de 50 ")
console.log(dez + " notas de 10 ")
console.log(cinco + " notas de 5 ")
console.log(um + " notas de 1 ")